In [20]:
import numpy as np

In [78]:
class LinearRegression():
  def __init__(self):
    self.w = None
    self.b = None

  def fit(self, x_train, y_train, lr=0.001, epochs=1000):
    row, col = x_train.shape
    self.w = np.random.rand(col)
    self.b = np.random.rand()
    for epoch in range(epochs):
      y_pred = self.predict(x_train)
      dw = (-2/row) * np.dot(x_train.T, (y_train - y_pred))
      db = (-2/row) * np.sum(y_train - y_pred)
      self.w = self.w - lr * dw
      self.b = self.b - lr * db

  def predict(self, x_test):
    return x_test @ self.w + self.b

In [79]:
np.random.seed(42)
X = 2 * np.random.rand(100, 2)  # Biến độc lập với 2 đặc trưng
y = 4 + 3 * X[:, 0] + 2 * X[:, 1] + np.random.randn(100)  # Biến phụ thuộc với noise
print(X.shape)
print(y.shape)

# Huấn luyện mô hình
model = LinearRegression()
model.fit(X, y)

# Dự đoán
X_test = np.linspace(0, 2, 100).reshape(-1, 2)
print('x', X_test.shape)
y_pred = model.predict(X_test)

# In hệ số hồi quy
print(f'Hệ số hồi quy (w): {model.w}')
print(f'Hệ số chặn (b): {model.b}')

(100, 2)
(100,)
x (50, 2)
Hệ số hồi quy (w): [0.95486528 0.73789692]
Hệ số chặn (b): [0.55435405]


In [45]:
import numpy as np
a = 1 + np.array([[1, 2, 3],
                  [3, 4, 5]])
print(a)

[[2 3 4]
 [4 5 6]]


In [65]:
a = np.random.rand(5)
b = np.random.rand(5, 1)
c = a @ b
print(a)
print(b)
print(c.shape)
print(c)

[0.09444296 0.68300677 0.07118865 0.31897563 0.84487531]
[[0.02327194]
 [0.81446848]
 [0.28185477]
 [0.11816483]
 [0.69673717]]
(1,)
[1.20489795]
